language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - make clean
  - NODE_ENV=production make build
  - make ga

after_success:
  - test $TRAVIS_BRANCH == "master" && ./_deploy
