name: Node

on: [push]

jobs:
  cache_node_modules:
    name: Cache node_modules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn install --frozen-lockfile

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: cache_node_modules
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn prettier --check *.html src
