name: Node

on: [push]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10

    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-v1-

    - run: yarn install

    - name: yarn prettier
      run: yarn prettier --check *.html src
